spring.application.name=project-iku
logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=project_iku;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123

# Hibernate KHÔNG t? t?o / drop b?ng
# Ch? ki?m tra entity có kh?p v?i DB hay không
spring.jpa.hibernate.ddl-auto=validate

# Không cho Spring ch?y schema.sql / data.sql
spring.sql.init.mode=never

# Không trì hoãn datasource initialization
spring.jpa.defer-datasource-initialization=false

# Hi?n th? câu SQL Hibernate sinh ra
spring.jpa.show-sql=true

# Dialect cho SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# ===============================
# LOGGING (DEV)
# ===============================

# Log SQL
logging.level.org.hibernate.SQL=debug

# Log bind parameter
logging.level.org.hibernate.type.descriptor.sql=trace

