spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=project_iku;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.pattern.console=${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %yellow(%-5level) %red([%thread]) %blue(%logger{255}) - %msg%n}
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace